Add logout function and an API call in SessionValid for session testing
Seagate/seagate-exos-x-api-go pull request #52
Opened 2023-12-04 21:09 UTC by David-T-White

Added a Logout call to the openAPI spec generation code to gracefully end API sessions. 

Also added a call to 'show system' in the SessionValid function as an additional test for validity.

2023-12-04 23:45 UTC, jskazinski requested changes
I have one question regarding the status returned from ShowVolumes() and one small cut-n-paste to correct.

2023-12-04 23:45 UTC, jskazinski commented on pkg/regression/v2_login.go
> +			logger.V(3).Info("Login", "ip", client.Addr, "username", client.Username, "err", err)
```suggestion
			logger.V(3).Info("Logout", "ip", client.Addr, "username", client.Username, "err", err)
```

2023-12-04 23:45 UTC, jskazinski commented on pkg/api/volumes.go
> +	status := &common.ResponseStatus{}
If response.Status is nil we return a default common.ResponseStatus(). Please look into either a) setting some values for common.ResponseStatus(), or b) changing CreateCommonStatus to handle a nil response.Status and filling in the correct common.ResponseStatus() to be returned to the caller.

2023-12-08 23:08 UTC, David-T-White commented on pkg/api/mcapi.go
> +	_, _, err := client.apiClient.DefaultApi.ShowSystemGet(client.Ctx).Execute()
Changed to use show controller-date which shows improved performance compared to show system.

2023-12-13 01:43 UTC, jskazinski approved these changes
Looks good, thanks David!

2024-01-19 22:19 UTC, merged